export { default as EditSvg } from './EditSvg';
export { default as LogoSvg } from './LogoSvg';
export { default as NoDataSvg } from './NoDataSvg';
export { default as CalendarSvg } from './CalendarSvg';
export { default as EmojiSvg } from './EmojiSvg';
export { default as ImageSvg } from './ImageSvg';
export { default as NotAllowedSvg } from './NotAllowedSvg';
export { default as XMarkSvg } from './XMarkSvg';
export { default as ArrowDownSvg } from './ArrowDownSvg';
